### ISSUE TITLE
OSError: [Errno 8] Exec format error: 'tools/linux/azcopy'

### ISSUE THREAD

**Issue by azzaj8** [microsoft/onefuzz#120]
## Information

- Onefuzz version: 1.2.0
- OS: macOS Catalina 10.15.5
- Python: 3.9.0
- Pip 20.2.3

## Provide detailed reproduction steps (if any)

Attempting to run the deployment scripts

1. brew reinstall python@3.9
2. echo 'export PATH="/usr/local/opt/python@3.9/bin:$PATH"' >> /Users/aaron/.bash_profile
3. close and re-open terminal 
4. pip3 install -r requirements.txt
5. python3 ./deploy.py uksouth fuzzit fuzzit <emailaddress>

### Expected result

Expected result is that the deployment completes and tools successfully upload.

### Actual result

MacBook-Pro:onefuzz-deployment-1.2.0 aaron$ Python3 ./deploy.py uksouth fuzzit fuzzit <emailaddress>
INFO:deploy:checking if RBAC already exists
INFO:deploy:Could not find the default CLI application under the current subscription, creating a new one
DEBUG:msrest.async_paging:Paging async iterator protocol is not available for ApplicationPaged
DEBUG:msrest.async_paging:Paging async iterator protocol is not available for ApplicationPaged
DEBUG:msrest.async_paging:Paging async iterator protocol is not available for ApplicationPaged
INFO:deploy:deploying arm template: azuredeploy.json
INFO:deploy:creating eventgrid destination queue
INFO:deploy:creating eventgrid subscription
INFO:deploy:uploading tools from tools
Traceback (most recent call last):
  File "/Users/aaron/Downloads/onefuzz-deployment-1.2.0/./deploy.py", line 753, in <module>
    main()
  File "/Users/aaron/Downloads/onefuzz-deployment-1.2.0/./deploy.py", line 747, in main
    state[1](client)
  File "/Users/aaron/Downloads/onefuzz-deployment-1.2.0/./deploy.py", line 478, in upload_tools
    subprocess.check_output(
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'tools/linux/azcopy'

**Comment by bmc-msft** [comment]
Thanks for the bug report.   At the moment, we re-use the azcopy bundled for the Azure VMs during the deployment phase.

Right now, we don't bundle a copy for OSX.

This should be straight forwards to address.
