### ISSUE TITLE
new deployments sometimes fail due to graph errors

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#1267]
## Information

- Onefuzz version: 3.0.0
- OS: linux

## Provide detailed reproduction steps (if any)

Performing an entirely new deployment (not reusing app registrations) in a new virtual environment, I get the following error on some deployments:

```
INFO:deploy:checking if RBAC already exists
INFO:deploy:creating Application registration
INFO:deploy:creating service principal
Traceback (most recent call last):
  File "deploy.py", line 1100, in <module>
    main()
  File "deploy.py", line 1094, in main
    state[1](client)
  File "deploy.py", line 411, in setup_rbac
    creds = list(client.applications.list_password_credentials(app.object_id))
  File "/tmp/tmpzp44a_ya/deploy-venv/lib/python3.8/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/tmp/tmpzp44a_ya/deploy-venv/lib/python3.8/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/tmp/tmpzp44a_ya/deploy-venv/lib/python3.8/site-packages/azure/graphrbac/operations/applications_operations.py", line 697, in internal_paging
    raise models.GraphErrorException(self._deserialize, response)
azure.graphrbac.models.graph_error_py3.GraphErrorException: Resource '92be41a5-63bb-4e16-80ae-860a5697463a' does not exist or one of its queried reference-property objects are not present.
```

### Expected result

Deployment to succeed.

### Actual result

Exceptions as shown 

AB#39994190

**Comment by bmc-msft** [comment]
cc: @chkeita
