### ISSUE TITLE
deployments fail with HashConflictOnDifferentRoleAssignmentIds errors

### ISSUE THREAD

**Issue by bmc-msft** [microsoft/onefuzz#1272]
Doing a green-field deployment is failing with this error:

```
INFO:deploy:checking if RBAC already exists
INFO:deploy:creating Application registration
INFO:deploy:creating service principal
INFO:deploy:app password created
INFO:deploy:deploying arm template: azuredeploy.json

Traceback (most recent call last):
  File "/tmp/tmplye2wlof/deploy-venv/lib/python3.8/site-packages/azure/core/polling/base_polling.py", line 483, in run
    self._poll()
  File "/tmp/tmplye2wlof/deploy-venv/lib/python3.8/site-packages/azure/core/polling/base_polling.py", line 522, in _poll
    raise OperationFailed("Operation failed or canceled")
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deploy.py", line 1091, in <module>
    main()
  File "deploy.py", line 1085, in main
    state[1](client)
  File "deploy.py", line 540, in deploy_template
    raise error
  File "deploy.py", line 516, in deploy_template
    result = client.deployments.begin_create_or_update(
  File "/tmp/tmplye2wlof/deploy-venv/lib/python3.8/site-packages/azure/core/polling/_poller.py", line 255, in result
    self.wait(timeout)
  File "/tmp/tmplye2wlof/deploy-venv/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/tmp/tmplye2wlof/deploy-venv/lib/python3.8/site-packages/azure/core/polling/_poller.py", line 275, in wait
    raise self._exception # type: ignore
  File "/tmp/tmplye2wlof/deploy-venv/lib/python3.8/site-packages/azure/core/polling/_poller.py", line 192, in _start
    self._polling_method.run()
  File "/tmp/tmplye2wlof/deploy-venv/lib/python3.8/site-packages/azure/core/polling/base_polling.py", line 501, in run
    raise HttpResponseError(
azure.core.exceptions.HttpResponseError: (DeploymentFailed) At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
Code: DeploymentFailed
Message: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
Exception Details:      (BadRequest) {
          "error": {
            "code": "HashConflictOnDifferentRoleAssignmentIds",
            "message": "A hash conflict was encountered for the role Assignment ID. Please use a new Guid."
          }
        }
        Code: BadRequest
        Message: {
          "error": {
            "code": "HashConflictOnDifferentRoleAssignmentIds",
            "message": "A hash conflict was encountered for the role Assignment ID. Please use a new Guid."
          }
        }
```

**Comment by chkeita** [comment]
@bmc-msft can you please add the deployment log from the azure portal that will help us identify which resource is failing

**Comment by bmc-msft** [comment]
Unfortunately, I am not able to do that.  The deployments got automatically cleaned up on failure.

**Comment by ranweiler** [comment]
@stishkin, can we assign this to you, since you've investigated the upstream issue?

**Comment by stishkin** [comment]
@ranweiler  Assigned to myself
