### ISSUE TITLE
Task failed due to `azcopy` panic

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#1386]
**Version:** OneFuzz 3.2.0
**Task:** `libfuzzer_fuzz`
**OS:** Windows

A task failed due to a panic in `azcopy`. The top-level error message was:
> " log:"unable to read azcopy log file from: no log file in path: C:\Windows\TEMP\.tmprEYDzc

**Note:** this error message comes from our `azcopy` wrapper, [here](https://github.com/microsoft/onefuzz/blob/b238bfea03e2ee470642a5454de5d039f809a43d/src/agent/onefuzz/src/az_copy.rs#L57).

Details:
<details>
<summary>Stack trace</summary>

```
 [running]:
runtime.systemstack_switch()
        /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/asm_amd64.s:339 fp=0xc0005ef598 sp=0xc0005ef590 pc=0xa0fb00
runtime.(*mheap).alloc(0x1cc9960, 0xc4, 0x100, 0xc0005ef688)
        /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/mheap.go:904 +0x88 fp=0xc0005ef5e8 sp=0xc0005ef598 pc=0x9c9388
runtime.(*mcache).allocLarge(0x2d693d70108, 0x186a00, 0x1, 0x2d693d70108)
        /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/mcache.go:224 +0x9e fp=0xc0005ef640 sp=0xc0005ef5e8 pc=0x9b949e
runtime.mallocgc(0x186a00, 0x151e300, 0xc0000d2901, 0xc0005f0000)
        /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/malloc.go:1078 +0x965 fp=0xc0005ef6c8 sp=0xc0005ef640 pc=0x9aed25
runtime.makechan(0x13a9f40, 0x186a0, 0xc0000621e0)
        /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/chan.go:106 +0x154 fp=0xc0005ef710 sp=0xc0005ef6c8 pc=0x9a59d4
github.com/Azure/azure-storage-azcopy/v10/ste.initJobsAdmin(0x16cca68, 0xc0000a80f0, 0x20, 0xc0003ccdb0, 0xc0003ccde0, 0xc0003cce10, 0xc0003cce40, 0x20, 0x7ffffe58, 0xc0003cce70, ...)
        /home/vsts/work/1/s/ste/JobsAdmin.go:142 +0x156 fp=0xc0005ef888 sp=0xc0005ef710 pc=0x12523d6
github.com/Azure/azure-storage-azcopy/v10/ste.MainSTE(0x20, 0xc0003ccdb0, 0xc0003ccde0, 0xc0003cce10, 0xc0003cce40, 0x20, 0x7ffffe58, 0xc0003cce70, 0x0, 0xc0000bf500, ...)
        /home/vsts/work/1/s/ste/init.go:61 +0xe5 fp=0xc0005ef9f0 sp=0xc0005ef888 pc=0x125afc5
github.com/Azure/azure-storage-azcopy/v10/cmd.glob..func5(0xc0003d7900, 0xc0003d4400, 0x2, 0x4, 0x0, 0x0)
        /home/vsts/work/1/s/cmd/root.go:114 +0x348 fp=0xc0005efc00 sp=0xc0005ef9f0 pc=0x130b0e8
github.com/spf13/cobra.(*Command).execute(0xc0003d7900, 0xc0003d43c0, 0x4, 0x4, 0xc0003d7900, 0xc0003d43c0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:835 +0x582 fp=0xc0005efcc0 sp=0xc0005efc00 pc=0x123b2a2
github.com/spf13/cobra.(*Command).ExecuteC(0x1ca3e20, 0x52b4c8eaa1f10677, 0x30, 0x14733c0)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375 fp=0xc0005efda0 sp=0xc0005efcc0 pc=0x123bdb5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/Azure/azure-storage-azcopy/v10/cmd.Execute(0xc0000d26f0, 0x30, 0xc0000a7140, 0x1a, 0xc0000bf500, 0x36, 0x7fffffff)
        /home/vsts/work/1/s/cmd/root.go:165 +0xfa fp=0xc0005efe40 sp=0xc0005efda0 pc=0x12e473a
main.main()
        /home/vsts/work/1/s/main.go:82 +0x397 fp=0xc0005eff88 sp=0xc0005efe40 pc=0x1328897
runtime.main()
        /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:225 +0x256 fp=0xc0005effe0 sp=0xc0005eff88 pc=0x9ddab6
runtime.goexit()
        /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0005effe8 sp=0xc0005effe0 pc=0xa119a1

goroutine 19 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000e6100)
        /home/vsts/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xd4
created by go.opencensus.io/stats/view.init.0
        /home/vsts/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x72

goroutine 20 [chan receive]:
github.com/Azure/azure-storage-azcopy/v10/common.(*lifecycleMgr).processOutputMessage(0xc0002e2070)
        /home/vsts/work/1/s/common/lifecyleMgr.go:341 +0x94
created by github.com/Azure/azure-storage-azcopy/v10/common.glob..func1
        /home/vsts/work/1/s/common/lifecyleMgr.go:35 +0x1a7

goroutine 21 [sleep]:
time.Sleep(0x7a120)
        /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/time.go:193 +0xe5
github.com/Azure/azure-storage-azcopy/v10/common.(*lifecycleMgr).watchInputs(0xc0002e2070)
        /home/vsts/work/1/s/common/lifecyleMgr.go:107 +0x3b6
created by github.com/Azure/azure-storage-azcopy/v10/common.glob..func1
        /home/vsts/work/1/s/common/lifecyleMgr.go:38 +0x1c9

goroutine 22 [sleep]:
time.Sleep(0x4a817c800)
        /opt/hostedtoolcache/go/1.16.0/x64/src/runtime/time.go:193 +0xe5
main.configureGC.func1()
        /home/vsts/work/1/s/main.go:91 +0x37
created by main.configureGC
        /home/vsts/work/1/s/main.go:90 +0x3c
" log:"unable to read azcopy log file from: no log file in path: C:\Windows\TEMP\.tmprEYDzc"
```
</details> 

AB#39994072

**Comment by mgreisen** [comment]
Closing for now as we haven't seen this issue in a long time. Will re-open if we see it again.
