### ISSUE TITLE
onefuzz cli discards stderr output from azcopy

### ISSUE THREAD

**Issue by anflanne** [microsoft/onefuzz#1512]
## Information

- Onefuzz version: 4.0.0
- OS: Windows

## Provide detailed reproduction steps (if any)

1. Submit onefuzz job
2. have azcopy fail
3. observe output from CLI

because onefuzz cli uses subprocess.check_output() to run azcopy, stderr gets discarded.

### Expected result

If azcopy fails, the data from stderr should be passed back to the user

### Actual result

Only stdout is shown to the user, discarding error messages potentially useful for troubleshooting.

Example:

ERROR:__main__:Failed to execute command "['C:\\Users\\comcma\\.azcopy\\AzCopy.exe', 'sync', 'C:\\_work\\22\\XXXXX\\plugin\\continuous-fuzzing\\onefuzz-deploy\\onefuzz-setup', 'XXXXX', '--recursive=true']". stdout: "b"INFO: Any empty folders will not be processed, because source and/or destination doesn't have full folder support

Job b3a3b9c7-fc30-954a-6137-fe6604946d58 has started
Log file is located at: C:\\Users\\comcma\\.azcopy\\b3a3b9c7-fc30-954a-6137-fe6604946d58.log

0 Files Scanned at Source, 0 Files Scanned at Destination
INFO: AzCopy.exe: A newer version 10.13.0 is available to download

0 Files Scanned at Source, 0 Files Scanned at Destination
0.2 %, 28 Done, 1 Failed, 11 Pending, 40 Total, 2-sec Throughput (Mb/s): 1845.4263
4.1 %, 35 Done, 1 Failed, 4 Pending, 40 Total, 2-sec Throughput (Mb/s): 3860.1553 
4.9 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2814.9933
8.7 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3474.0406
11.7 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2563.0196
15.1 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3207.0888
19.0 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3501.1619
21.7 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2488.6603
24.9 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2984.8678
28.7 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3527.8311
32.4 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3363.0054
36.0 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3374.8095
40.1 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3639.0506
43.6 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3204.426 
46.5 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2709.4768
49.5 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2756.3732
52.7 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3021.2756
56.5 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3494.6863
58.7 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2059.5965
62.0 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3077.1736
66.0 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3628.0642
69.1 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2906.1173
70.6 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 1408.3869
72.9 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2097.6759
75.8 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2663.3646
78.9 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 2830.7833
82.4 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 3269.9332
87.1 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 4375.3138
87.9 %, 36 Done, 1 Failed, 3 Pending, 40 Total, 2-sec Throughput (Mb/s): 788.9237 
89.8 %, 37 Done, 1 Failed, 2 Pending, 40 Total, 2-sec Throughput (Mb/s): 1743.9527
92.6 %, 37 Done, 1 Failed, 2 Pending, 40 Total, 2-sec Throughput (Mb/s): 2526.4545
95.1 %, 37 Done, 1 Failed, 2 Pending, 40 Total, 2-sec Throughput (Mb/s): 2266.9438
97.5 %, 37 Done, 1 Failed, 2 Pending, 40 Total, 2-sec Throughput (Mb/s): 322.2314 
99.5 %, 37 Done, 1 Failed, 2 Pending, 40 Total, 2-sec Throughput (Mb/s): 0       
100.0 %, 38 Done, 1 Failed, 1 Pending, 40 Total, 2-sec Throughput (Mb/s): 0

Job b3a3b9c7-fc30-954a-6137-fe6604946d58 Summary
Files Scanned at Source: 40
Files Scanned at Destination: 0
Elapsed Time (Minutes): 1.2102
Number of Copy Transfers for Files: 40
Number of Copy Transfers for Folder Properties: 0 
Total Number Of Copy Transfers: 40
Number of Copy Transfers Completed: 39
Number of Copy Transfers Failed: 1
Number of Deletions at Destination: 0
Total Number of Bytes Transferred: 23144592322
Total Number of Bytes Enumerated: 29023206850
Final Job Status: CompletedWithErrors

"", stderr: "None"
Traceback (most recent call last):
  File "C:\_work\22\XXXXX\onefuzz\XXXXX.py", line 238, in main
    setup_shared_containers(
  File "C:\_work\22\XXXXX\onefuzz\XXXXX.py", line 555, in setup_shared_containers
    job_helper.onefuzz.containers.files.upload_dir(
  File "C:\Program Files\Python39\lib\site-packages\onefuzz\api.py", line 229, in upload_dir
    client.upload_dir(dir_path)
  File "C:\Program Files\Python39\lib\site-packages\onefuzz\backend.py", line 378, in upload_dir
    azcopy_sync(dir_path, self.container_url)
  File "C:\Program Files\Python39\lib\site-packages\onefuzz\azcopy.py", line 29, in azcopy_sync
    subprocess.check_output([azcopy, "sync", src, dst, "--recursive=true"])  # nosec
  File "C:\Program Files\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\comcma\\.azcopy\\AzCopy.exe', 'sync', 'C:\\_work\\22\\XXXXX\\plugin\\continuous-fuzzing\\onefuzz-deploy\\onefuzz-setup', 'XXXXXXX', '--recursive=true']' returned non-zero exit status 1.
INFO:__main__:Deleting job f25a00f8-1345-4136-805

**Comment by anflanne** [comment]
note:
check_output can capture stderr if configured to do so:

"To also capture standard error in the result, use stderr=subprocess.STDOUT" - https://docs.python.org/3/library/subprocess.html?highlight=subprocess#subprocess.check_output
