### ISSUE TITLE
deploy.py throws Subscription Not found In Azure Gov Cloud 

### ISSUE THREAD

**Issue by Chaos-Monkey-Island** [microsoft/onefuzz#1678]
- Onefuzz version: Current download on 22/02/2022 
- OS: Windows 10 

## Provide detailed reproduction steps (if any)

1. Follow Getting started guide
2. Verify that all four resource providers are properly registered:
   •	Microsoft.EventGrid
•	Microsoft.Network
•	Microsoft.Compute
•	Microsoft.SignalRService
4.  Login with AZ LOGIN, returns OK
5.  Run [ az account list ] to verify default subscription
6.  Launch deploy.py 

### Expected result

Deploy.py will create the VM's and return 00. 

### Actual result
 File "C:\Python37\lib\site-packages\azure\core\exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (SubscriptionNotFound) The subscription 'f279200d-f856-457b-8b80-XXXXXXXXXXXX' could not be found.
Code: SubscriptionNotFound

Is OneFuzz available in GOVCLOUD?

**Comment by Chaos-Monkey-Island** [comment]
Additional traceback:

Traceback (most recent call last):
  File "deploy.py", line 1218, in <module>
    main()
  File "deploy.py", line 1212, in main
    state[1](client)
  File "deploy.py", line 210, in check_region
    location = self.get_location_display_name()
  File "deploy.py", line 200, in get_location_display_name
    for location in locations:
  File "C:\Python37\lib\site-packages\azure\core\paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "C:\Python37\lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "C:\Python37\lib\site-packages\azure\mgmt\resource\subscriptions\v2021_01_01\operations\_subscriptions_operations.py", line 116, in get_next
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "C:\Python37\lib\site-packages\azure\core\exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (SubscriptionNotFound)

**Comment by mgreisen** [comment]
@Chaos-Monkey-Island 
1. try setting active subscription explicitly. i.e. `az account set --subscription mysububscription`
2. Have you verified your RBAC permissions on the subscription?
