### ISSUE TITLE
Integration tests polling failing with timeout

### ISSUE THREAD

**Issue by mgreisen** [microsoft/onefuzz#1683]
## Information

- Onefuzz version: 5.1.0
- OS: Windows & Linux

## Provide detailed reproduction steps (if any)

1.Run the multi-stage check-pr pipeline and select all the integration tests

### Expected result

All the tests pass.

### Actual result

Only a few pass and the rest fail with a server 500 error. The tests poll the jobs/tasks every second. With each poll multiple GET requests are issued. The failing jobs have this failing data:

```
2022-03-01T22:11:00.3420190Z DEBUG:nsv-backend:request GET https://check-pr2-8232-1-dd5e8a6e-f0e5-562f-5c8f-6123c6bdff29.azurewebsites.net/api/scaleset {'scaleset_id': None, 'state': None, 'include_auth': False}
2022-03-01T22:11:00.5274210Z DEBUG:nsv-backend:request GET https://check-pr2-8232-1-dd5e8a6e-f0e5-562f-5c8f-6123c6bdff29.azurewebsites.net/api/tasks {'task_id': '4a99212d-d936-48a3-b255-654f9990c56d'}
2022-03-01T22:11:00.7015956Z DEBUG:nsv-backend:request GET https://check-pr2-8232-1-dd5e8a6e-f0e5-562f-5c8f-6123c6bdff29.azurewebsites.net/api/tasks {'task_id': 'dd0ccec6-d6cc-4f9c-9323-593416eb40bb'}
2022-03-01T22:11:01.8657159Z DEBUG:nsv-backend:request GET https://check-pr2-8232-1-dd5e8a6e-f0e5-562f-5c8f-6123c6bdff29.azurewebsites.net/api/scaleset {'scaleset_id': None, 'state': None, 'include_auth': False}
2022-03-01T22:11:02.0528398Z DEBUG:nsv-backend:request GET https://check-pr2-8232-1-dd5e8a6e-f0e5-562f-5c8f-6123c6bdff29.azurewebsites.net/api/tasks {'task_id': '4a99212d-d936-48a3-b255-654f9990c56d'}
2022-03-01T22:11:02.2281493Z DEBUG:nsv-backend:request GET https://check-pr2-8232-1-dd5e8a6e-f0e5-562f-5c8f-6123c6bdff29.azurewebsites.net/api/tasks {'task_id': 'dd0ccec6-d6cc-4f9c-9323-593416eb40bb'}
2022-03-01T22:11:02.3639825Z ERROR:cli:traceback: Traceback (most recent call last):
2022-03-01T22:11:02.3641917Z ERROR:cli:traceback:   File "/home/vsts/work/1/s/.env/lib/python3.8/site-packages/onefuzz/cli.py", line 586, in execute_api
2022-03-01T22:11:02.3642964Z ERROR:cli:traceback:     result = call_func(args.func, args)
2022-03-01T22:11:02.3644347Z ERROR:cli:traceback:   File "/home/vsts/work/1/s/.env/lib/python3.8/site-packages/onefuzz/cli.py", line 74, in call_func
2022-03-01T22:11:02.3645636Z ERROR:cli:traceback:     return func(**myargs)
2022-03-01T22:11:02.3646805Z ERROR:cli:traceback:   File "integration-test.py", line 1065, in check_results
2022-03-01T22:11:02.3647621Z ERROR:cli:traceback:     self.check_jobs(
2022-03-01T22:11:02.3648723Z ERROR:cli:traceback:   File "integration-test.py", line 924, in check_jobs
2022-03-01T22:11:02.3649534Z ERROR:cli:traceback:     result = tester.check_jobs(
2022-03-01T22:11:02.3650664Z ERROR:cli:traceback:   File "integration-test.py", line 585, in check_jobs
2022-03-01T22:11:02.3651522Z ERROR:cli:traceback:     return wait(check_jobs_impl)
2022-03-01T22:11:02.3653328Z ERROR:cli:traceback:   File "/home/vsts/work/1/s/.env/lib/python3.8/site-packages/onefuzz/backend.py", line 472, in wait
2022-03-01T22:11:02.3654267Z ERROR:cli:traceback:     result = func()
2022-03-01T22:11:02.3655372Z ERROR:cli:traceback:   File "integration-test.py", line 524, in check_jobs_impl
2022-03-01T22:11:02.3656327Z ERROR:cli:traceback:     task_result = self.check_task(jobs[job_id], task, scalesets)
2022-03-01T22:11:02.3662047Z ERROR:cli:traceback:   File "integration-test.py", line 426, in check_task
2022-03-01T22:11:02.3663080Z ERROR:cli:traceback:     task = self.of.tasks.get(task.task_id)
2022-03-01T22:11:02.3664441Z ERROR:cli:traceback:   File "/home/vsts/work/1/s/.env/lib/python3.8/site-packages/onefuzz/api.py", line 790, in get
2022-03-01T22:11:02.3665378Z ERROR:cli:traceback:     return self._req_model(
2022-03-01T22:11:02.3667135Z ERROR:cli:traceback:   File "/home/vsts/work/1/s/.env/lib/python3.8/site-packages/onefuzz/api.py", line 109, in _req_model
2022-03-01T22:11:02.3668444Z ERROR:cli:traceback:     response = self.onefuzz._backend.request(method, endpoint, json_data=data)
2022-03-01T22:11:02.3669961Z ERROR:cli:traceback:   File "/home/vsts/work/1/s/.env/lib/python3.8/site-packages/onefuzz/backend.py", line 331, in request
2022-03-01T22:11:02.3670896Z ERROR:cli:traceback:     raise Exception(
2022-03-01T22:11:02.3671970Z ERROR:cli:traceback: Exception: request did not succeed: HTTP 500 - 
2022-03-01T22:11:02.3672665Z ERROR:cli:traceback: 
2022-03-01T22:11:02.3673641Z ERROR:cli:command failed: request did not succeed: HTTP 500 - 
```

Looking in AppInsights there is a single failure that happens 17 times. 

```
System.TimeoutException:
   at Microsoft.Azure.WebJobs.Extensions.Storage.TimeoutHandler+<ExecuteWithTimeout>d__1`1.MoveNext (Microsoft.Azure.WebJobs.Extensions.Storage, Version=3.0.11.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\TimeoutHandler.cs:30)
```

The exception message is
`The operation 'GetMessages' with id '608cb662-5817-46f6-bb2e-53f6ac9f3775' did not complete in '00:02:00'.`

and the custom formatted message is:
`An unhandled exception has occurred. Host is shutting down.`

I'm wondering if it's possible there is a table query that is resulting in a table scan for these GET requests.  

AB#39993824

**Comment by mgreisen** [comment]
This appears to have been addressed as we haven't seen this failure in some time.
