### ISSUE TITLE
Latest 5.5.0 release fails to deploy due to a 400 Bad Request error in the new C# code

### ISSUE THREAD

**Issue by puhley** [microsoft/onefuzz#1970]
## Information

- Onefuzz version: 5.5
- OS: Executed from a Mac laptop

## Provide detailed reproduction steps (if any)

1. When upgrading OneFuzz, the new C# code fails to deploy properly:

```
./deploy.py $REGION $RESOURCE_GROUP_NAME $ONEFUZZ_INSTANCE_NAME $CONTACT_EMAIL_ADDRESS $NSG_CONFIG_FILE
unable to use built-in azcopy, using system install
INFO:deploy:Could not find the default CLI application under the current subscription, creating a new one
INFO:deploy:removing deprecated event subscription
INFO:deploy:deploying arm template: azuredeploy-bicep.json
INFO:deploy:assigning the user managed identity role
INFO:deploy:assinging user access to service principal
WARNING:deploy:The service is not currently configured to require a role assignment to access it. This means that any authenticated user can access the service.  To change this behavior enable 'Assignment Required?' on the service principal in the AAD Portal.
INFO:deploy:applying database migrations
INFO:deploy:setting instance config
INFO:deploy:deploying arm template: ./config.json
INFO:deploy:uploading tools from tools
INFO:deploy:setting instance_id log export
INFO:deploy:instance_id: 12d34aa56-123d-1fb2-b123-1f2a3db4e567
INFO:deploy:uploading instance-specific-setup from instance-specific-setup
INFO:deploy:uploading third-party tools from third-party
INFO:deploy:deploying function app api-service.zip
INFO:deploy:deploying function app api-service-net.zip 
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 340
   at Azure.Functions.Cli.Helpers.AzureHelper.PrintFunctionsInfo(Site functionApp, String accessToken, String managementURL, Boolean showKeys) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 463
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 495
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 184
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
WARNING:deploy:function failed to deploy, waiting 60 seconds and trying again
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 340
   at Azure.Functions.Cli.Helpers.AzureHelper.PrintFunctionsInfo(Site functionApp, String accessToken, String managementURL, Boolean showKeys) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 463
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 495
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 184
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
WARNING:deploy:function failed to deploy, waiting 60 seconds and trying again
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 340
   at Azure.Functions.Cli.Helpers.AzureHelper.PrintFunctionsInfo(Site functionApp, String accessToken, String managementURL, Boolean showKeys) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 463
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 495
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 184
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
WARNING:deploy:function failed to deploy, waiting 60 seconds and trying again
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Azure.Functions.Cli.Helpers.AzureHelper.ArmHttpAsync[T](HttpMethod method, Uri uri, String accessToken, Object payload) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 340
   at Azure.Functions.Cli.Helpers.AzureHelper.PrintFunctionsInfo(Site functionApp, String accessToken, String managementURL, Boolean showKeys) in D:\a\1\s\src\Azure.Functions.Cli\Helpers\AzureHelper.cs:line 463
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.PublishFunctionApp(Site functionApp, GitIgnoreParser ignoreParser, IDictionary`2 additionalAppSettings) in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 495
   at Azure.Functions.Cli.Actions.AzureActions.PublishFunctionAppAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\AzureActions\PublishFunctionAppAction.cs:line 184
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
Traceback (most recent call last):
  File "./deploy.py", line 1307, in <module>
    main()
  File "./deploy.py", line 1301, in main
    state[1](client)
  File "./deploy.py", line 1066, in deploy_dotnet_app
    raise error
  File "./deploy.py", line 1043, in deploy_dotnet_app
    subprocess.check_output(
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/func', 'azure', 'functionapp', 'publish', 'our-onefuzz-deploy-net', '--no-build']' returned non-zero exit status 1.
```

### Expected result

A clean upgrade from the previous version to the current version.

### Actual result

The configuration process for the api-service-net.zip file encounters a 400 Bad Request error and the deployment fails.

**Comment by puhley** [comment]
Potential user error on my part. I tried updating my Python dependencies and deploying again. It worked the second time.
