### ISSUE TITLE
create_pool_registration deployment issue where resource does not exist when called in create_application_registration()

### ISSUE THREAD

**Issue by anslutsk** [microsoft/onefuzz#212]
## Information

- Onefuzz version: 1.4.0
- OS: Windows

## Provide detailed reproduction steps (if any)

1. Creating a pool registration fails the first time I do a deployment. I think it's due to creating the an application and then immediately running az_cli to do the "rest" call in register_pool_application:create_application_registration() but of course, it works perfectly if I run the deployment script again. I have reproduced the issue several times. 

### Expected result

Successful deployment 

### Actual result

$  python deploy.py westus2 example01 example01 "email@microsoft.com" --export_appinsights --create_pool_registration True
INFO:deploy:checking if RBAC already exists
...
<all expected to this point>
...
INFO:deploy:deploying function app api-service.zip
INFO:deploy:adding appinsight log export
INFO:deploy:Updating application registration
DEBUG:msrest.async_paging:Paging async iterator protocol is not available for ApplicationPaged
DEBUG:msrest.async_paging:Paging async iterator protocol is not available for ApplicationPaged
ERROR:cli.azure.cli.core.azclierror:Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '<ID>' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2020-10-27T07:37:50",
      "request-id": "<ID>",
      "client-request-id": "<ID>"
    }
  }
})
Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '<ID>' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2020-10-27T07:37:50",
      "request-id": "<ID>",
      "client-request-id": "<ID>"
    }
  }
})
Traceback (most recent call last):
  File "deploy.py", line 792, in <module>
    main()
  File "deploy.py", line 786, in main
    state[1](client)
  File "deploy.py", line 614, in update_registration
    update_registration(self.application_name)
  File "C:\Users\anslutsk\of_onefuzz\1_4_0_onefuzz_1_4_0\DEPLOY\register_pool_application.py", line 259, in update_registration
    onefuzz_instance_name=application_name,
  File "C:\Users\anslutsk\of_onefuzz\1_4_0_onefuzz_1_4_0\DEPLOY\register_pool_application.py", line 55, in register_application
    app = create_application_registration(onefuzz_instance_name, registration_name)
  File "C:\Users\anslutsk\of_onefuzz\1_4_0_onefuzz_1_4_0\DEPLOY\register_pool_application.py", line 149, in create_application_registration
    json.dumps(body),
  File "C:\Users\anslutsk\of_onefuzz\1_4_0_onefuzz_1_4_0\DEPLOY\register_pool_application.py", line 35, in az_cli
    raise cli.result.error
  File "C:\Program Files\Python37\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 654, in execute
    raise ex
  File "C:\Program Files\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\Program Files\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "C:\Program Files\Python37\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Program Files\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "C:\Program Files\Python37\lib\site-packages\azure\cli\core\commands\__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\azure\cli\core\__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "C:\Program Files\Python37\lib\site-packages\azure\cli\command_modules\util\custom.py", line 17, in rest_call
    skip_authorization_header, resource, output_file)
  File "C:\Program Files\Python37\lib\site-packages\azure\cli\core\util.py", line 905, in send_raw_request
    raise CLIError(reason)
knack.util.CLIError: Not Found({
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource '<ID>' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "date": "2020-10-27T07:37:50",
      "request-id": "<ID>",
      "client-request-id": "<ID>"
    }
  }
})

**Comment by chkeita** [comment]
will be handled in #236

**Comment by chkeita** [comment]
fixed in #236
