### ISSUE TITLE
Add a troubleshooting guide for authentication issues

### ISSUE THREAD

**Issue by chkeita** [microsoft/onefuzz#319]
Add to the documentation the steps to fix authentication issues during deployments

**Comment by chkeita** [comment]
one issue that needs to be address is this error message when deploying 
```
INFO:deploy:checking if RBAC already exists
INFO:deploy:deploying arm template: azuredeploy.json
INFO:deploy:assigning the user managed identity role
Traceback (most recent call last):
  File "deploy.py", line 857, in <module>
    main()
  File "deploy.py", line 851, in main
    state[1](client)
  File "deploy.py", line 410, in assign_scaleset_identity_role
    assign_scaleset_role(
  File "/tmp/release/deploy/registration.py", line 371, in assign_scaleset_role
    query_microsoft_graph(
  File "/tmp/release/deploy/registration.py", line 66, in query_microsoft_graph
    raise GraphQueryError(
registration.GraphQueryError: request did not succeed: HTTP 403 - {
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "date": "2020-11-17T16:57:10",
      "request-id": "d3e59410-5b15-4cf0-b129-35ff1daea420",
      "client-request-id": "d3e59410-5b15-4cf0-b129-35ff1daea420"
    }
  }
}
```
