### ISSUE TITLE
Connection reset error while running the deploy.py script

### ISSUE THREAD

**Issue by Ashutosh-18-hub** [microsoft/onefuzz#3210]
## Information

- Onefuzz version:
- OS: Ubuntu 20.04 

## Provide detailed reproduction steps (if any)

1. ./deploy.py $REGION $RESOURCE_GROUP_NAME $ONEFUZZ_INSTANCE_NAME $CONTACT_EMAIL_ADDRESS $NSG_CONFIG_FILE
2.
3.

### Expected result

Instance of onefuzz deployed on Azure.

### Actual result

Getting below error-

INFO:deploy:parsing config: config.json
Traceback (most recent call last):
  File "./deploy.py", line 1399, in <module>
    main()
  File "./deploy.py", line 1393, in main
    state[1](client)
  File "./deploy.py", line 244, in check_region
    location = self.get_location_display_name()
  File "./deploy.py", line 234, in get_location_display_name
    for location in locations:
  File "/usr/local/lib/python3.8/dist-packages/azure/core/paging.py", line 124, in __next__
    return next(self._page_iterator)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/usr/local/lib/python3.8/dist-packages/azure/mgmt/resource/subscriptions/v2021_01_01/operations/_operations.py", line 280, in get_next
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 202, in run
    return first_node.send(pipeline_request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.8/dist-packages/azure/mgmt/core/policies/_base.py", line 46, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/policies/_redirect.py", line 156, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/policies/_retry.py", line 470, in send
    raise err
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/policies/_retry.py", line 448, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/policies/_authentication.py", line 113, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 70, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 101, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/transport/_requests_basic.py", line 364, in send
    raise error
azure.core.exceptions.ServiceResponseError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

[#AB154028](https://dev.azure.com/fuzzfest/Onefuzz/_workitems/edit/154028)

**Comment by nharper285** [comment]
Hi Ashutosh!

Did you give this deployment a retry? If so, did you see this exact error every time?

**Comment by Ashutosh-18-hub** [comment]
> 

Yes,I did retry multiple times, and getting the same error as above

**Comment by nharper285** [comment]
Can you walk me through the steps you took to deploy? Did you login via the az cli?

**Comment by Ashutosh-18-hub** [comment]
Login is failing when I am using the wsl2.
I am using command az login.

Error details are as below:



root@IN-20815L3:~# az --version
azure-cli                         2.49.0

core                              2.49.0
telemetry                          1.0.8

Dependencies:
msal                              1.20.0
azure-mgmt-resource               22.0.0

Python location '/usr/bin/python3'
Extensions directory '/root/.azure/cliextensions'

Python (Linux) 3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
root@IN-20815L3:~#
root@IN-20815L3:~#
root@IN-20815L3:~#
root@IN-20815L3:~# az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
The command failed with an unexpected error. Here is the traceback:
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/command_modules/profile/custom.py", line 139, in login
    subscriptions = profile.login(
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/_profile.py", line 154, in login
    user_identity = identity.login_with_auth_code(scopes=scopes, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/azure/cli/core/auth/identity.py", line 153, in login_with_auth_code
    result = self._msal_app.acquire_token_interactive(
  File "/usr/local/lib/python3.8/dist-packages/msal/application.py", line 1828, in acquire_token_interactive
    response = _clean_up(self.client.obtain_token_by_browser(
  File "/usr/local/lib/python3.8/dist-packages/msal/oauth2cli/oidc.py", line 281, in obtain_token_by_browser
    return super(Client, self).obtain_token_by_browser(
  File "/usr/local/lib/python3.8/dist-packages/msal/oauth2cli/oauth2.py", line 639, in obtain_token_by_browser
    return self._obtain_token_by_browser(
  File "/usr/local/lib/python3.8/dist-packages/msal/oauth2cli/oauth2.py", line 677, in _obtain_token_by_browser
    return self.obtain_token_by_auth_code_flow(
  File "/usr/local/lib/python3.8/dist-packages/msal/application.py", line 142, in obtain_token_by_auth_code_flow
    return super(_ClientWithCcsRoutingInfo, self).obtain_token_by_auth_code_flow(
  File "/usr/local/lib/python3.8/dist-packages/msal/oauth2cli/oidc.py", line 205, in obtain_token_by_auth_code_flow
    result = super(Client, self).obtain_token_by_auth_code_flow(
  File "/usr/local/lib/python3.8/dist-packages/msal/oauth2cli/oauth2.py", line 547, in obtain_token_by_auth_code_flow
    return self._obtain_token_by_authorization_code(
  File "/usr/local/lib/python3.8/dist-packages/msal/oauth2cli/oauth2.py", line 731, in _obtain_token_by_authorization_code
    return self._obtain_token("authorization_code", data=data, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/msal/oauth2cli/oidc.py", line 116, in _obtain_token
    ret = super(Client, self)._obtain_token(grant_type, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/msal/oauth2cli/oauth2.py", line 771, in _obtain_token
    resp = super(Client, self)._obtain_token(
  File "/usr/local/lib/python3.8/dist-packages/msal/oauth2cli/oauth2.py", line 234, in _obtain_token
    resp = (post or self._http_client.post)(
  File "/usr/local/lib/python3.8/dist-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/msal/individual_cache.py", line 269, in wrapper
    value = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
root@IN-20815L3:~#

**Comment by Ashutosh-18-hub** [comment]
> Ashutosh, it's difficult for me to understand exactly what's going on with your az CLI implementation on wsl2.
> 
> Is there a reason you aren't trying to deploy from windows, though?


Login is successful through windows and even using azure cli docker image . But in docker, azure function core tools are not being installed due to missing dependencies. Could you suggest any more efficient platform to deploy the onefuzz??

**Comment by nharper285** [comment]
Is there a reason you're trying to deploy using an azure cli docker image and not just through Windows? 

You should be able to download the azure function core tools and the requirements.txt file via pip with no issue. Then run the deploy script in Windows.

**Comment by Ashutosh-18-hub** [comment]
After running the deploy script in windows , getting the below permission error:-

INFO:deploy:parsing config: config.json
INFO:deploy:creating Application registration
Traceback (most recent call last):
  File "C:\Users\pandeyas\Documents\Onefuzz\deploy.py", line 1399, in <module>
    main()
  File "C:\Users\pandeyas\Documents\Onefuzz\deploy.py", line 1393, in main
    state[1](client)
  File "C:\Users\pandeyas\Documents\Onefuzz\deploy.py", line 377, in setup_rbac
    app = self.create_new_app_registration(app_roles)
  File "C:\Users\pandeyas\Documents\Onefuzz\deploy.py", line 573, in create_new_app_registration
    app = query_microsoft_graph(
  File "C:\Users\pandeyas\Documents\Onefuzz\deploylib\registration.py", line 81, in query_microsoft_graph
    raise GraphQueryError(
deploylib.registration.GraphQueryError: request did not succeed: HTTP 403 - {"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"date":"2023-07-02T13:14:08","request-id":"d3ca8e5a-b935-4adb-b3f0-1b8cbf098c3c","client-request-id":"d3ca8e5a-b935-4adb-b3f0-1b8cbf098c3c"}}}

**Comment by Ashutosh-18-hub** [comment]
Also, I am trying to deploy onefuzz using Free Trial subsciption. Is free trial subscription enough to deploy the onefuzz or we need paid subscription for deploying??

**Comment by nharper285** [comment]
Hm I'm not actually sure if it will work on a trial subscription. Regardless, the error you're getting is because you haven't logged into your azure account via the az cli. 

If you take a look at these [instructions](https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md#deploying-an-instance-of-onefuzz), you'll see that one of the first steps in logging in.
