### ISSUE TITLE
Getting started using OneFuzz fails first deployment on deploy.py, line 238, in get_location_display_name

### ISSUE THREAD

**Issue by jasonsketchup** [microsoft/onefuzz#3233]
## Information

- Onefuzz version: 8.3.0
- OS: Linux ubuntu 5.19.0-45-generic 22.04.1-Ubuntu [...]

## Provide detailed reproduction steps (if any)

1.  AZ Login...
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
```
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "REDACTED",
    "id": "REDACTED",
    "isDefault": true,
    "managedByTenants": [],
    "name": "REDACTED",
    "state": "Enabled",
    "tenantId": "REDACTED",
    "user": {
      "name": "REDACTED",
      "type": "user"
    }
  }
]
```
3.  Export env vars...
```
export REGION='uswest2'
export RESOURCE_GROUP_NAME='resource_group'
export ONEFUZZ_INSTANCE_NAME='onefuzz'
export NSG_CONFIG_FILE=deploy.json
```
5.  Create config file...
```
cat << EoF > "$NSG_CONFIG_FILE"
{
    "tenant_id": "${tenantId}",
    "tenant_domain": "${tenant_domain}",
    "multi_tenant_domain": "",
    "proxy_nsg_config": {
        "allowed_ips": [
            "*"
        ],
        "allowed_service_tags": []
    }
}
EoF
```
7.  Run `deploy.py`...
```
./deploy.py $REGION $RESOURCE_GROUP_NAME $ONEFUZZ_INSTANCE_NAME $CONTACT_EMAIL_ADDRESS $NSG_CONFIG_FILE --verbose --auto_create_cli_app
```

### Expected result

_What is the expected result of the above steps?_  First OneFuzz deployment success. This has never worked.

### Actual result

_What is the actual result of the above steps?_
```
Installing Bicep CLI v0.18.4...
The configuration value of bicep.use_binary_from_path has been set to 'false'.
Successfully installed Bicep CLI to "/home/jantona/.azure/bin/bicep".
/home/jantona/Projects/onefuzz-deployment-8.3.0/azuredeploy.bicep(190,5) : Warning use-resource-id-functions: If property "roleDefinitionId" represents a resource ID, it must use a symbolic resource reference, be a parameter or start with one of these functions: extensionResourceId, guid, if, reference, resourceId, subscription, subscriptionResourceId, tenantResourceId. [https://aka.ms/bicep/linter/use-resource-id-functions]
/home/jantona/Projects/onefuzz-deployment-8.3.0/azuredeploy.bicep(205,5) : Warning use-resource-id-functions: If property "roleDefinitionId" represents a resource ID, it must use a symbolic resource reference, be a parameter or start with one of these functions: extensionResourceId, guid, if, reference, resourceId, subscription, subscriptionResourceId, tenantResourceId. [https://aka.ms/bicep/linter/use-resource-id-functions]
/home/jantona/Projects/onefuzz-deployment-8.3.0/azuredeploy.bicep(206,18) : Warning use-resource-symbol-reference: Use a resource reference instead of invoking function "reference". This simplifies the syntax and allows Bicep to better understand your deployment dependency graph. [https://aka.ms/bicep/linter/use-resource-symbol-reference]
/home/jantona/Projects/onefuzz-deployment-8.3.0/bicep-templates/function.bicep(114,29) : Warning use-resource-symbol-reference: Use a resource reference instead of invoking function "reference". This simplifies the syntax and allows Bicep to better understand your deployment dependency graph. [https://aka.ms/bicep/linter/use-resource-symbol-reference]

INFO:deploy:parsing config: deploy.json
INFO:azure.core.pipeline.policies.http_logging_policy:Request URL: 'https://management.azure.com/subscriptions/7eefac52-77f7-47cc-a57d-bf529be7cabf/locations?api-version=REDACTED'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': 'fbeb8c2c-1505-11ee-a9db-7198afe78549'
    'User-Agent': 'azsdk-python-azure-mgmt-resource/22.0.0 Python/3.10.6 (Linux-5.19.0-45-generic-x86_64-with-glibc2.35)'
    'Authorization': 'REDACTED'
No body was attached to the request
INFO:azure.core.pipeline.policies.http_logging_policy:Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Content-Encoding': 'REDACTED'
    'Expires': '-1'
    'Vary': 'REDACTED'
    'x-ms-ratelimit-remaining-subscription-reads': '11999'
    'x-ms-request-id': '7823f07a-c82f-4601-9f68-943df60bb961'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-routing-request-id': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Tue, 27 Jun 2023 16:16:35 GMT'
    'Content-Length': '5034'
Traceback (most recent call last):
  File "./deploy.py", line 1399, in <module>
    main()
  File "./deploy.py", line 1393, in main
    state[1](client)
  File "./deploy.py", line 244, in check_region
    location = self.get_location_display_name()
  File "/home/jantona/Projects/onefuzz-deployment-8.3.0/./deploy.py", line 238, in get_location_display_name
    raise Exception("unknown location: %s", self.location)
Exception: ('unknown location: %s', 'uswest2')
```

[AB#156734](https://fuzzfest.visualstudio.com/5eaacf23-2084-4d62-8fbe-7d37326a8b74/_workitems/edit/156734)

**Comment by jasonsketchup** [comment]
Appears `westcentralus` is a valid value for `$REGION`.

**Comment by nharper285** [comment]
Hi @jasonsketchup, looks like you input uswest2 for the location of the first deployment. The correct location is `westus2`.

**Comment by jasonsketchup** [comment]
For reference, accepted `$REGION` values are:
```
australiacentral
australiacentral2
australiaeast
australiasoutheast
brazilsouth
brazilsoutheast
canadacentral
canadaeast
centralindia
centralus
eastasia
eastus
eastus2
francecentral
francesouth
germanynorth
germanywestcentral
japaneast
japanwest
jioindiacentral
jioindiawest
koreacentral
koreasouth
northcentralus
northeurope
norwayeast
norwaywest
polandcentral
qatarcentral
southafricanorth
southafricawest
southcentralus
southeastasia
southindia
swedencentral
switzerlandnorth
switzerlandwest
uaecentral
uaenorth
uksouth
ukwest
westeurope
westus
westus2
westus3
```

Ty-ty, @nharper285 .
