### ISSUE TITLE
OneFuzz 2.0 Initial Deployment Error "InvalidAppId"

### ISSUE THREAD

**Issue by Sinderella** [microsoft/onefuzz#486]
## Information

- OneFuzz version: 2.0.0
- OS: Tried on both macOS and Azure console "Common Base Linux Delridge (quinault)"

## Provide detailed reproduction steps (if any)

1. Download the deployment artifact and install the requirements using `pipenv install`
2. Deploy OneFuzz using the command as shown in the section below.

### Expected result

For it to be deployed, the same steps (with different venv) could deploy version 1.11.0.

### Actual result

```
(onefuzz) user@Azure:~/onefuzz$ python deploy.py northeurope user_group <redacted>-onefuzz <redacted>@....com
INFO:deploy:checking if RBAC already exists
INFO:deploy:creating Application registration
INFO:deploy:creating service principal
Traceback (most recent call last):
  File "deploy.py", line 902, in <module>
    main()
  File "deploy.py", line 896, in main
    state[1](client)
  File "deploy.py", line 349, in setup_rbac
    authorize_application(onefuzz_cli_app_uuid, app.app_id)
  File "/home/user/onefuzz/registration.py", line 340, in authorize_application
    "preAuthorizedApplications": preAuthorizedApplications.to_list()
  File "/home/user/onefuzz/registration.py", line 79, in query_microsoft_graph
    response.status_code,
registration.GraphQueryError: request did not succeed: HTTP 400 - {
  "error": {
    "code": "InvalidAppId",
    "message": "Property PreAuthorizedApplication references applications 72f1562a-8c0c-41ea-beb9-fa2b71c80134 that cannot be found.",
    "innerError": {
      "date": "2021-01-29T16:24:51",
      "request-id": "9253d1ee-4992-4a39-8c22-6add7ff311eb",
      "client-request-id": "9253d1ee-4992-4a39-8c22-6add7ff311eb"
    },
    "details": [
      {
        "target": "api.preAuthorizedApplications.appId",
        "code": "InvalidValue"
      }
    ]
  }
}
```

Thank you!

**Comment by bmc-msft** [comment]
@chkeita, Please take a look at this issue.

**Comment by bmc-msft** [comment]
@Sinderella, 2.1.0 should fix the issue you've identified.  Please re-open this issue if the problem persists.
