### ISSUE TITLE
can't install onefuzz-2.10

### ISSUE THREAD

**Issue by adrian-rt** [microsoft/onefuzz#734]
## Information

- Onefuzz version:2.10
- OS: Ubuntu 20

## Provide detailed reproduction steps (if any)

1.cd src/cli ; sudo python3 setup.py install
2.
3.

### Expected result

_What is the expected result of the above steps?_

### Actual result
Running pycparser-2.20/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1ctq8r7c/cryptography-3.3.2/temp/easy_install-57haap5y/pycparser-2.20/egg-dist-tmp-_876y376
warning: no previously-included files found matching 'setup.pyc'
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...

    =============================DEBUG ASSISTANCE=============================
    If you are seeing a compilation error please try the following steps to
    successfully install cryptography:
    1) Upgrade to the latest pip and try again. This will fix errors for most
       users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
    2) Read https://cryptography.io/en/latest/installation.html for specific
       instructions for your platform.
    3) Check our frequently asked questions for more information:
       https://cryptography.io/en/latest/faq.html
    =============================DEBUG ASSISTANCE=============================
    
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 157, in save_modules
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 255, in run_setup
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 285, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 253, in runner
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/tmp/easy_install-1ctq8r7c/cryptography-3.3.2/temp/easy_install-57haap5y/pycparser-2.20/setup.py", line 35, in <module>
    description="Onefuzz Client Library for Python",
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 209, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 245, in zip_safe
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 355, in analyze_egg
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 392, in scan_module
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 157, in save_modules
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 255, in run_setup
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 285, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 253, in runner
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/tmp/easy_install-1ctq8r7c/cryptography-3.3.2/setup.py", line 44, in <module>
    install_requires=requirements,
  File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/dist.py", line 317, in __init__
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/dist.py", line 369, in fetch_build_eggs
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/__init__.py", line 846, in resolve
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/__init__.py", line 1118, in best_match
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/__init__.py", line 1130, in obtain
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/dist.py", line 440, in fetch_build_egg
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 674, in easy_install
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 700, in install_item
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 881, in install_eggs
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 1120, in build_and_install
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 1106, in run_setup
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 258, in run_setup
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 169, in save_modules
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 144, in resume
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/_vendor/six.py", line 685, in reraise
    
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 157, in save_modules
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 255, in run_setup
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 285, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 253, in runner
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/tmp/easy_install-1ctq8r7c/cryptography-3.3.2/temp/easy_install-57haap5y/pycparser-2.20/setup.py", line 35, in <module>
    description="Onefuzz Client Library for Python",
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 209, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 245, in zip_safe
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 355, in analyze_egg
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 392, in scan_module
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    setuptools.setup(
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/install.py", line 67, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/install.py", line 117, in do_egg_install
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 411, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 655, in easy_install
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 702, in install_item
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 746, in process_distribution
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/__init__.py", line 846, in resolve
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/__init__.py", line 1118, in best_match
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/__init__.py", line 1130, in obtain
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 674, in easy_install
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 700, in install_item
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 881, in install_eggs
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 1120, in build_and_install
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 1106, in run_setup
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 258, in run_setup
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 169, in save_modules
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 144, in resume
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/_vendor/six.py", line 685, in reraise
    
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 157, in save_modules
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 255, in run_setup
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 285, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 253, in runner
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/tmp/easy_install-1ctq8r7c/cryptography-3.3.2/setup.py", line 44, in <module>
    install_requires=requirements,
  File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/dist.py", line 317, in __init__
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/dist.py", line 369, in fetch_build_eggs
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/__init__.py", line 846, in resolve
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/__init__.py", line 1118, in best_match
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/__init__.py", line 1130, in obtain
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/dist.py", line 440, in fetch_build_egg
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 674, in easy_install
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 700, in install_item
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 881, in install_eggs
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 1120, in build_and_install
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/easy_install.py", line 1106, in run_setup
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 258, in run_setup
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 169, in save_modules
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 144, in resume
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/pkg_resources/_vendor/six.py", line 685, in reraise
    
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 157, in save_modules
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 198, in setup_context
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 255, in run_setup
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 285, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 253, in runner
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/sandbox.py", line 47, in _execfile
  File "/tmp/easy_install-1ctq8r7c/cryptography-3.3.2/temp/easy_install-57haap5y/pycparser-2.20/setup.py", line 35, in <module>
    description="Onefuzz Client Library for Python",
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 209, in run
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 245, in zip_safe
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 355, in analyze_egg
  File "/usr/local/lib/python3.8/dist-packages/setuptools-33.1.1-py3.8.egg/setuptools/command/bdist_egg.py", line 392, in scan_module
ValueError: bad marshal data (unknown type code)

**Comment by chkeita** [comment]
Have you installed the prerequisite from the requirements file before deploying ?
Could your python installation be corrupted ([see](https://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data)) ?

**Comment by adrian-rt** [comment]
@chkeita ah, forgot to add, doing pip install -r requirements.txt in the clif folder gives me this error:

ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 515, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python3/dist-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/usr/lib/python3/dist-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/wrappers.py", line 160, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/tmp/tmp3ong6c95", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools.build_meta'

I've upgraded my pip, setuptools, etc nothing worked

**Comment by chkeita** [comment]
it looks like your installation is missing setuptools try installing it first with 
`sudo apt-get install python3-setuptools`

**Comment by ranweiler** [comment]
@adrian-rt, please share how you created the virtualenv, as well.

After activating the virtualenv, you may want to try upgrading to a newer (virtualenv-local) copy of `setuptools`, e.g.:
```
python3.7 -m venv vev
. venv/bin/activate
pip install --upgrade setuptools
# ... continue from here
```

**Comment by adrian-rt** [comment]
@ranweiler  I didn't create one, I tried to follow somewhat the instructions from https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md but I guess maybe those are a bit outdated?

 now after I have setup the enviroment and upgraded setuptools I get the followin errors:

If I do pip3 install -r requirements in the cli folder: 
ERROR: Could not find a version that satisfies the requirement onefuzztypes==0.0.0 (from -r requirements.txt (line 20)) (from versions: 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.10.0)
ERROR: No matching distribution found for onefuzztypes==0.0.0 (from -r requirements.txt (line 20))

I have modified the requirements to change the version for onefuzztypes to 2.10.0 and then get this error:

  ERROR: Command errored out with exit status 1:
   command: /home/adrian/Downloads/tools/onefuzz-2.10.0/src/cli/vev/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lf3ncfih/future/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lf3ncfih/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-kyj8v9u9
       cwd: /tmp/pip-install-lf3ncfih/future/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for future

I tried to do pip3 install -r requirements.txt and it worked without any error, however when I do sudo python3 setup.py install 
I get the bad marshall data error agian. 

I ran the find /usr -name '*.pyc' -delete but still doesn't work.

**Comment by adrian-rt** [comment]
ps: I think I found an easy solution with pip3 install onefuzz :)

**Comment by ranweiler** [comment]
Generally comment: our instructions actually indicate using `pip` to install in the first place, whereas it looks like you were initially using `python3` directly against the `setup.py` for the CLI package. It doesn't look like you installed the `onefuzztypes` package first, which may have been one your problems.

But first, let's validate the existing Getting Started instructions. I confirmed that to install the OneFuzz CLI, the following works on a fresh Ubuntu 20.04 VM, using OneFuzz release 2.10.0:
```bash
# Sync apt repo
$ sudo apt update
# WARNING: optional, will upgrade all system packages, but I did this step
$ # sudo apt upgrade
# install the `venv` module: https://docs.python.org/3/library/venv.html
$ sudo apt install python3-venv
# create a virtualenv named `venv`
$ python3 -m venv venv
# Activate the virtual env in your shell session.
$ . venv/bin/activate
# Check that we have the latest `onefuzz-...whl` and `onefuzztypes...whl` packages downloaded.
(venv) $ ls onefuzz*.whl
onefuzz-2.10.0-py3-none-any.whl  onefuzztypes-2.10.0-py3-none-any.whl
# Install them.
(venv) $ pip install onefuzz*.whl
# Check that the `onefuzz` CLI is now in the path, because it was installed to our virtualenv
(venv) $ which onefuzz
/home/joe/venv/bin/onefuzz
# Check the version
(venv) $ onefuzz --version
onefuzz 2.10.0
```
I did not install any Ubuntu Python packages other than what is listed above (`python3-venv`). Small modifications might be needed for different versions or distros.

The virtual environment is not essential, but I *strongly* recommend it to isolate dependencies, avoid conflicts with other applications, and enable easy upgrades. If you _really_ want to install the CLI more globally, you should install `python3-pip` (as you observed), and do:
```bash
$ sudo apt install python3-pip
# Assumes both the `onefuzz` and `onefuzztypes` wheels are in the current dir, as above.
$ pip3 install onefuzz*whl
# Binaries get installed by `pip` to `$HOME/.local/bin`
$ ./local/bin/onefuzz --version
onefuzz 2.10.0
```

Second, @adrian-rt, OneFuzz is a system primarily designed to orchestrate fuzzing in Azure. The CLI tool really just makes HTTP calls to various endpoints. These CLI- and SDK-facing endpoints (+ orchestration logic and the resources they manage) are contained in a single Azure Resource Group, which you must deploy. This is described in the Getting Started Guide, and is exactly what it means to ["deploy an instance of OneFuzz"](https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md#deploying-an-instance-of-onefuzz).

I've created #745 to capture ways we can add more documentation for specific installation scenarios, perhaps using some of my above commentary as a starting point. I believe this issue is resolved, so please open a new one if you have trouble deploying using the Getting Started guide. I recommend using a virtualenv for the deploy script, too.
