### ISSUE TITLE
Deploy fails on Linux if missing `$HOME/.local/share`

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#899]
### Problem

With all pre-requisites installed, invoking `deploy.py` failed with the following error:
```
INFO:deploy:deploying function app api-service.zip
System.Exception: Cannot find the Local Application Data.
   at Azure.Functions.Cli.Utilities.EnsureCoreToolsLocalData() in D:\a\1\s\src\Azure.Functions.Cli\Common\Utilities.cs:line 180
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.StorageService.VerifyOrSetDefaultStorageDirectoryPath(String desireStorageDirectoryPath) in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\StorageService.cs:line 96
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.StorageService.Init(String storageDirectoryPath) in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\StorageService.cs:line 78
   at Azure.Functions.Cli.Telemetry.PersistenceChannel.PersistenceChannel..ctor(String storageDirectoryPath, Int32 sendersCount) in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\PersistenceChannel\PersistenceChannel.cs:line 42
   at Azure.Functions.Cli.Telemetry.Telemetry.InitializeTelemetry() in D:\a\1\s\src\Azure.Functions.Cli\Telemetry\Telemetry.cs:line 93
```
This is due to an empty result when resolving the `LocalApplicationData` special folder [here](https://github.com/Azure/azure-functions-core-tools/blob/735920bfbeac5d79eb3c978047301f1cd9957dcd/src/Azure.Functions.Cli/Common/Utilities.cs#L179).

On Linux, this .NET enum should resolve to the value of `XDG_DATA_HOME`, which [defaults](https://github.com/dotnet/runtime/blob/64f5f0b31d9af2df199229e6e4ef3f4a876a05a5/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L103-L110) to `$HOME/.local/share`. Setting `XDG_DATA_HOME` to a non-default but existing directory resulted in the same error, but ensuring the existence of the default directory did unblock deployment.

Related (closed) upstream issue: dotnet/runtime#27582.

### System
**OneFuzz:** 2.16.0
**OS:** Ubuntu 18.04 (WSL1)
**Packages:**
- `azure-cli`: 2.23.0
- `azure-functions-core-tools-3`: 3.0.3442-1
- `python`: 3.7.5

**Comment by ranweiler** [comment]
This is not a bug in our script, but does impact us, so opening for visibility, mitigation, later follow-up.

**Comment by ranweiler** [comment]
Seen again on WSL2, `azure-functions-core-tools` 3.0.3785.

**Comment by Ashutosh-18-hub** [comment]
I am not able to run the deploy command for deploying the instance of onefuzz for the first time. I am getting the following error- 
"azure-functions-core-tools" not installed.

When trying to install the azure function core tools, it is throwing a lot of errors saying "missing dependencies"

Is there any better way to install the tools and dependencies together?

I am using the below environment-
Ubuntu WSL 20.04
Azure CLI docker image.

**Comment by tevoinea** [comment]
@Ashutosh-18-hub Are you following these instructions to install azure function core tools? https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Clinux%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools

An alternative is to use the devcontainer we've created for this repository which comes preinstalled with dotnet/python/az cli/azure function core tools. Please let us know if you have trouble deploying from the devcontainer/codespaces for this repository.
