### ISSUE TITLE
`target_env` argument parsing has undocumented usage constraints

### ISSUE THREAD

**Issue by ranweiler** [microsoft/onefuzz#906]
An internal user ran into this.

**OS:** Windows 10
**Shell:** PowerShell 5 
**OneFuzz:** 2.17.0

### Repro
~~1. Using `pip` associated with a Python **3.9** install (check via `pip --version`), install the OneFuzz CLI via the `.whl`, as described in the getting started guide.~~ (**edit:** this was not relevant)
2. Try to create a job (say, a `libfuzzer basic`) with `--target_env` setting an `ASAN_OPTIONS` variable with an `=` sign in the _value_, e.g. `ASAN_OPTIONS=allocator_may_return_null=1`. Have the positional args occur immediately after the `--target_env` arg, but do not bind `--target_env` itself with an `=`. For example:
```
onefuzz template libfuzzer basic --target ./fuzz.exe --target_env ASAN_OPTIONS=allocator_may_return_null=1 project job build pool`
```

### Expected

Job gets created, tasks have `target_env` with an `ASAN_OPTIONS` key set to `allocator_may_return_null=1`.

### Actual

CLI throws an execption with an `argparse` error like:
```
Traceback (most recent call last):
  File "<..>\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "<..>\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "<..>\Python\Python39\Scripts\onefuzz.exe\__main__.py", line 7, in <module>
  File "<..>\python39\lib\site-packages\onefuzz\__main__.py", line 16, in main
    return execute_api(Onefuzz(), [Endpoint, Command], __version__)
  File "<..>\python39\lib\site-packages\onefuzz\cli.py", line 520, in execute_api
    args = builder.parse_args()
  File "<..>\python39\lib\site-packages\onefuzz\cli.py", line 461, in parse_args
    return self.main_parser.parse_args()
  File "<..>\python39\lib\argparse.py", line 1818, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "<..>\python39\lib\argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "<..>\python39\lib\argparse.py", line 2042, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "<..>\python39\lib\argparse.py", line 2019, in consume_positionals
    take_action(action, args)
  File "<..>\python39\lib\argparse.py", line 1928, in take_action
    action(self, namespace, argument_values, option_string)
  File "<..>\python39\lib\argparse.py", line 1207, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "<..>\python39\lib\argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "<..>\python39\lib\argparse.py", line 2042, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "<..>\python39\lib\argparse.py", line 2019, in consume_positionals
    take_action(action, args)
  File "<..>\python39\lib\argparse.py", line 1928, in take_action
    action(self, namespace, argument_values, option_string)
  File "<..>\python39\lib\argparse.py", line 1207, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "<..>\python39\lib\argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "<..>\python39\lib\argparse.py", line 2042, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "<..>\python39\lib\argparse.py", line 2019, in consume_positionals
    take_action(action, args)
  File "<..>\python39\lib\argparse.py", line 1928, in take_action
    action(self, namespace, argument_values, option_string)
  File "<..>\python39\lib\argparse.py", line 1207, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "<..>\python39\lib\argparse.py", line 1851, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "<..>\python39\lib\argparse.py", line 2060, in _parse_known_args
    start_index = consume_optional(start_index)
  File "<..>\python39\lib\argparse.py", line 2000, in consume_optional
    take_action(action, args, option_string)
  File "<..>\python39\lib\argparse.py", line 1928, in take_action
    action(self, namespace, argument_values, option_string)
  File "<..>\python39\lib\site-packages\onefuzz\cli.py", line 306, in __call__
    as_dict: Dict[str, str] = {
  File "<..>\python39\lib\site-packages\onefuzz\cli.py", line 306, in <dictcomp>
    as_dict: Dict[str, str] = {
ValueError: not enough values to unpack (expected 2, got 1)
```

### Comment

The user was following the [getting-started](https://github.com/microsoft/onefuzz/blob/main/docs/getting-started.md) guide, which only specifies Python >= 3.7 (in the deployment section), with no upper bound.

**Comment by bmc-msft** [comment]
The underlying issue isn't 3.9.  It's there for 3.8 as well.

This works:
```
onefuzz template libfuzzer basic a a a linux --target_env ASAN_OPTIONS=allocator_may_return_null=1
```

This does not:
```
onefuzz template libfuzzer basic --target_env ASAN_OPTIONS=allocator_may_return_null=1 a a a linux
```

Note, this also works:

```
onefuzz template libfuzzer basic --target_env=ASAN_OPTIONS=allocator_may_return_null=1 a a a linux
```

**Comment by ranweiler** [comment]
Thanks for double-checking.

For me, a very minor variant of your second example did work:
```
onefuzz template libfuzzer basic --target_exe fuz.exe --inputs .\corpus --target_env ASAN_OPTIONS=max_allocation_size_mb=1024:allocator_may_return_null=1 --vm_count 1 p j b windows
```
If I remove `--vm_count`, it does not. So I'm guessing the issue, most specifically, is that the positional args cannot occur _directly_ after an arg whose value contains `=` signs?

The exact form of the failing invocation for the user was:
```
onefuzz template libfuzzer basic --setup_dir D:\fuzz --colocate_all_tasks --vm_count 1 --target_exe D:\fuzz\fuzzer.exe --inputs D:\fuzz\seeds --target_env ASAN_OPTIONS=max_allocation_size_mb=1024:allocator_may_return_null=1 $PROJECT $JOB $BUILD $POOL
```

**Comment by bmc-msft** [comment]
I've spent a bit more time digging into argparse.  It is complicated by the intermingling of positional and non-positional arguments.

 `--target_env` followed by `--vm_count` works because `--vm_count` is another argument that consumes a single value.
