### ISSUE TITLE
Windows call stack and ASAN log report are not symbolized in ADO notification

### ISSUE THREAD

**Issue by jagunter** [microsoft/onefuzz#93]
The stacks in the ADO notification are not symbolized, both in the call stack and the ASAN log. However, if running the fuzzer on the crash input on a onefuzz host directly (e.g. over ssh), the reported stacks are symbolized. Verified the relevant PDBs are in the uploaded setup container.

Relevant portion of ADO notification configuration:

```
"This is the call stack: <ul> {% for item in report.call_stack %} <li> {{ item }} </li> {% endfor %} </ul>ASan log:<br>{{ report.asan_log }}"
```

Actual notification:

```
This is the call stack:

    #0 0x12344321 (dll+0x12344321)
    #1 0x12344321 (dll+0x12344321)
...
ASan log:
...

==2500==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x12344321 at pc 0x12344321 bp 0x12344321 sp 0x12344321
READ of size N at 0x12344321 thread T0
    #0 0x12344321 (dll+0x12344321)
    #1 0x12344321 (dll+0x12344321)
...

0x12344321 is located 0 bytes to the right of N-byte region [0x12344321,0x12344321 )
allocated by thread T0 here:
    #1 0x12344321 (dll+0x12344321)
    #2 0x12344321 (dll+0x12344321)
...
==2500==ABORTING
```

Expected:

```
This is the call stack:

    #0 0x12344321 in FunctionA sourceA.cpp:123
    #1 0x12344321 in FunctionB sourceB.cpp:456
...
ASan log:
...

==2500==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x12344321 at pc 0x12344321 bp 0x12344321 sp 0x12344321
READ of size N at 0x12344321 thread T0
    #0 0x12344321 in FunctionA sourceA.cpp:123
    #1 0x12344321 in FunctionB sourceB.cpp:456
...

0x12344321 is located 0 bytes to the right of N-byte region [0x12344321,0x12344321 )
allocated by thread T0 here:
    #1 0x12344321 in FunctionC sourceC.cpp:234
    #2 0x12344321 in FunctionD sourceD.cpp:567
...
==2500==ABORTING
```

**Comment by bmc-msft** [comment]
I believe this is an prerelease bug that was fixed in 1.0.0.  Once we are able to upgrade the prelease instances, we will verify and mark this closed.

**Comment by ranweiler** [comment]
Can we verify this is addressed, at least as of the latest release?

**Comment by ranweiler** [comment]
(cc @jagunter)
